### ISSUE TITLE
Selection error: Some nodes exists more than once

### ISSUE THREAD

**Issue by Dimchkin** [DreamWall-Animation/dwpicker#54] opened 2022-09-15 10:43 UTC
Hello!

Thanks for making DreamWall picker!

There is an issue I've been running into with different rigs:

After changing namespace for use with another character/rig, 99% gets changed correctly, but some picker controllers produce an error: `Selection error: Some nodes exists more than once: <Controller names>` and not working correctly unless changed manually.

Version: 0.6.0 and earlier

**Comment by luckylyk** [comment] 2022-10-27 13:47
Hi sorry for the very very long delay :/
Do you have a scene that I could analyse with the issue ?
If you can't provide the scene for nda reason, create a mockup with the issue is possible ?

**Comment by Dimchkin** [comment] 2022-10-27 17:11
Hi! No problem!

But yeah, unfortunately I can't share the scenes/rigs, nor possibility to provide a mockups. Sorry.

**Comment by luckylyk** [comment] 2022-11-07 10:39
I'm sorry, i will close this ticket without more way to reproduce.
Do not hesitate to reopen the ticket if you find some details about this which could helps to solve the issue or guide me to reproduce it.

**Closed by luckylyk** 2022-11-07 10:39 UTC
