### ISSUE TITLE
Unhandled Exception - ValueError

### ISSUE THREAD

**Issue by stickybullseye** [DreamWall-Animation/dwpicker#1] opened 2021-12-22 06:11 UTC
A very exciting AnimSchool Picker alternative! Unfortunately I encountered this "Unhandled Exception" when entering any value in the Picker Editor's text fields with a control button selected:
```
Traceback (most recent call last):
  File "/###/maya/scripts/dwpicker/widgets.py", line 148, in focusInEvent
    self._value = self.value()
  File "/###/maya/scripts/dwpicker/widgets.py", line 183, in value
    return int(self.text())
ValueError: invalid literal for int() with base 10: '10.0'
```
Maya 2020.4 on Linux. I'll try to recreate this issue on my home workstation as well. 
[edit] 
    Recreated the Unhandled Exception issue on Maya 2020.2 on Windows 11 by changing a value in Shape width/height fields
```
# Traceback (most recent call last):
#   File "C:/Users/aaron/Documents/maya/scripts\dwpicker\widgets.py", line 148, in focusInEvent
#     self._value = self.value()
#   File "C:/Users/aaron/Documents/maya/scripts\dwpicker\widgets.py", line 183, in value
#     return int(self.text())
# ValueError: invalid literal for int() with base 10: '20.0'
```
Copy paste buttons on editor's top menu bar didn't work, but CTRL+C and CTRL+V did the job
Command buttons didn't execute script - mel ```print "Button worked";``` 

Importing pkr files, adding background images, adjusting picker size, undo/redo, grid and the color wheels all worked perfectly.

**Comment by luckylyk** [comment] 2022-01-03 10:29
Oh sorry, i missed your message, I will fix that ASAP

**Comment by luckylyk** [comment] 2022-01-03 10:39
UPDATE sorry, i just fixed the unhandled exception.
I will check the other issues

**Comment by luckylyk** [comment] 2022-01-03 11:28
_Unhandled Exception - ValueError_
This is fixed in Release 0.0.3

_Copy paste buttons on editor's top menu bar didn't work, but CTRL+C and CTRL+V did the job_
I can't reproduce that issue, do you have more information ?

_Command buttons didn't execute script - mel print "Button worked";_
It seems that command were executed anymore. A simple mistake in a IF/ELSE tree
This is fixed in Release 0.0.3

**Comment by stickybullseye** [comment] 2022-01-04 00:54
Thanks for the update - I'll be using this daily! 0.0.3 is working as expected: 

- No Unhandled Exception error anymore when using editor's width/height fields
- Copy paste icons are working for me with this version
- Scripts execute in buttons 

Love your work!

**Comment by luckylyk** [comment] 2022-01-04 01:51
Hehe :) Thanks !
Good luck and dont forget to share that tool.

**Closed by luckylyk** 2022-01-04 01:51 UTC
