### ISSUE TITLE
Bugs about headers and the new namespace switching feature

### ISSUE THREAD

**Issue by plateauRen** [DreamWall-Animation/dwpicker#12] opened 2022-01-21 04:24 UTC
Hello, I have tested the new version and it is much better, but I found some new problems when making picker: 
1. When I modify the name or save or seve as the title, the modified version is always The first title,My selected title has not been modified， I think this is a bug; 
2. When I try the new namespace switching function, there will be a pop-up window for me to pop up the window again to let me modify the namespace, which should be a place to be improved

**Comment by luckylyk** [comment] 2022-01-22 14:03
1. I'm not sure, i can't reproduce on my side but i fixed something like this in previous version then i think it is ok now.
2. This is now fixed in new commit :)

Thanks for your precious time testing our tool !

**Closed by luckylyk** 2022-01-22 14:03 UTC
Labels: bug
